//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogIn_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_vw_InspectorView
    {
        public int Sent_ID { get; set; }
        public string PMs_Machines_ID { get; set; }
        public string عنوان_برنامه { get; set; }
        public string مجری { get; set; }
        public string نوع_فعالیت { get; set; }
        public string نتیجه { get; set; }
        public string تاریخ_اعلام_نتیجه { get; set; }
        public string کاربر_ثبت_کننده_نتیجه { get; set; }
        public string تاریخ_ثبت_نتیجه { get; set; }
        public string مقدار_جدید { get; set; }
        public string آیا_ریست_شده { get; set; }
        public string توضیحات { get; set; }
        public string نام_ماشین { get; set; }
        public string کد_ماشین { get; set; }
        public string مشخصه_تکمیلی_ماشین { get; set; }
        public string کد_ماشین_اولین_سطح { get; set; }
        public string نام_ماشین_اولین_سطح { get; set; }
        public string مشخصه_تکمیلی_ماشین_اولین_سطح { get; set; }
        public string کارگاه { get; set; }
        public Nullable<int> آخرین_مقدار { get; set; }
        public string واحد_مقدار { get; set; }
        public Nullable<bool> عدم_تائید_توسط_برنامه_ریزی_تعمیرات { get; set; }
        public string کاربر_برنامه_ریزی_تعمیرات { get; set; }
        public string تاریخ_ثبت_نظر { get; set; }
        public Nullable<bool> نظر_بازرس { get; set; }
        public string کاربر_بازرس { get; set; }
        public string تاریخ_ثبت_نظر_بازرس { get; set; }
        public string توضیحات_بازرس { get; set; }
        public string شماره_تیکت { get; set; }
        public string محل_استقرار { get; set; }
        public string زمان_مناسب_انجام_کار { get; set; }
    }
}
